<div class="container-fluid">
	<div class="row">
		<div class="col-lg-5 col-md-12 col-sm-12">
			<div class="col-lg-2 col-md-1 col-sm-1 text-blue">class</div>
			<div class="col-*-* text-green">ProfileModel</div>
			<div class="col-lg-12 col-md-12 col-sm-12 text-blank">{</div>
			<div class="col-lg-4 col-md-2 col-sm-3 ">
				<div class="col-lg-5 col-md-6 col-sm-6 text-red">public</div>
				<div class="col-lg-6 col-md-6 col-sm-6 text-blue">function</div>
			</div>
			<div class="col-*-* text-green">getName()</div>
			<div class="col-lg-12 col-md-12 col-sm-12">
				<div class="col-lg-12 col-md-12 col-sm-12 text-blank">{</div>
			</div>
			<div class="col-lg-12 col-md-12 col-sm-12">
				<div class="col-lg-3 col-md-2 col-sm-2 alignment-right">
					<div class="col-lg-7 col-md-7 col-sm-7 text-blank">$name</div>
					<div class="col-lg-2 col-md-2 col-sm-2 text-red">=</div>	
				</div>
				<div class="col-*-* text-yellow">"Luan Mark da Silva Borela";</div>
				<div class="col-lg-12 col-md-12 col-sm-12">
					<div class="col-lg-2 col-md-1 col-sm-2 text-red">return</div>
					<div class="col-lg-10 col-md-10 col-sm-10 text-blank alignment-left">$name;</div>
			</div>
			</div>
			<div class="col-lg-12 col-md-12 col-sm-12">
				<div class="col-lg-12 col-md-12 col-sm-12 text-blank">}</div>
			</div>



			<div class="col-lg-3 col-md-2 col-sm-3 new-block">
				<div class="col-lg-6 col-md-6 col-sm-6 text-red">public</div>
				<div class="col-lg-6 col-md-6 col-sm-6 text-blue">function</div>
			</div>
			<div class="col-lg-9 col-md-9 col-sm-9 text-green new-block">getDataDeNascimento()</div>
			<div class="col-lg-12 col-md-12 col-sm-12">
				<div class="col-lg-12 col-md-12 col-sm-12 text-blank">{</div>
			</div>
			<div class="col-lg-12 col-md-12 col-sm-12">
				<div class="col-lg-5 col-md-3 col-sm-2 alignment-right">
					<div class="col-lg-9 col-md-8 col-sm-7 text-blank">$dataNascimento</div>
					<div class="col-lg-2 col-md-1 col-sm-2 text-red">=</div>	
				</div>
				<div class="col-lg-2 col-md-1 col-sm-5 text-yellow alignment-left alignment-right">"14-11-1998"</div>
				<div class="col-lg-3 col-md-2 col-sm-2 text-comment">; //18 anos</div>
				<div class="col-lg-12 col-md-12 col-sm-12">
					<div class="col-lg-2 col-md-1 col-sm-2 text-red">return</div>
					<div class="col-lg-10 col-md-10 col-sm-10 text-blank alignment-left">$dataNascimento;</div>
				</div>
			</div>
			<div class="col-lg-12 col-md-12 col-sm-12">
				<div class="col-lg-12 col-md-12 col-sm-12 text-blank">}</div>
			</div>



			<div class="col-lg-3 col-md-2 col-sm-3 new-block">
				<div class="col-lg-6 col-md-6 col-sm-6 text-red">public</div>
				<div class="col-lg-6 col-md-6 col-sm-6 text-blue">function</div>
			</div>
			<div class="col-lg-9 col-md-9 col-sm-9 text-green new-block">getConhecimentos&Habilidades()</div>
			<div class="col-lg-12 col-md-12 col-sm-12">
				<div class="col-lg-12 col-md-12 col-sm-12 text-blank">{</div>
			</div>
			<div class="col-lg-12 col-md-12 col-sm-12">
				<div class="col-lg-5 col-md-2 col-sm-2 alignment-right">
					<div class="col-lg-9 col-md-9 col-sm-7 text-blank">$conhecimentos</div>
					<div class="col-lg-2 col-md-2 col-sm-2 text-red">=</div>	
				</div>
				<div class="col-lg-1 col-md-1 col-sm-5 text-blue alignment-left alignment-right">array</div>
				<div class="col-lg-3 col-md-2 col-sm-2 text-blank alignment-left">(</div>

				<div class="col-lg-12 col-md-12 col-sm-12 text-ident">
					<div class="col-lg-2 col-md-1 col-sm-2 text-yellow">"PHP"</div>
					<div class="col-lg-2 col-md-1 col-sm-2 text-red">=></div>
					<div class="col-*-* text-yellow">"++++++++++++++++++++",</div>

					<div class="col-lg-2 col-md-1 col-sm-2 text-yellow">"MVC"</div>
					<div class="col-lg-2 col-md-1 col-sm-2 text-red">=></div>
					<div class="col-*-* text-yellow">"++++++++++++++",</div>

					<div class="col-lg-2 col-md-1 col-sm-2 text-yellow">"PSRs"</div>
					<div class="col-lg-2 col-md-1 col-sm-2 text-red">=></div>
					<div class="col-*-* text-yellow">"+++++++++++++++",</div>

					<div class="col-lg-2 col-md-1 col-sm-2 text-yellow">"PDO"</div>
					<div class="col-lg-2 col-md-1 col-sm-2 text-red">=></div>
					<div class="col-*-* text-yellow">"+++++++++++++",</div>

					<div class="col-lg-2 col-md-1 col-sm-2 text-yellow">"Mysql"</div>
					<div class="col-lg-2 col-md-1 col-sm-2 text-red">=></div>
					<div class="col-*-* text-yellow">"+++++++++++",</div>

					<div class="col-lg-2 col-md-1 col-sm-2 text-yellow">"Java"</div>
					<div class="col-lg-2 col-md-1 col-sm-2 text-red">=></div>
					<div class="col-*-* text-yellow">"++++++++++",</div>

					<div class="col-lg-2 col-md-1 col-sm-2 text-yellow">"C"</div>
					<div class="col-lg-2 col-md-1 col-sm-2 text-red">=></div>
					<div class="col-*-* text-yellow">"+++++++",</div>

					<div class="col-lg-2 col-md-1 col-sm-2 text-yellow">"Arch"</div>
					<div class="col-lg-2 col-md-1 col-sm-2 text-red">=></div>
					<div class="col-*-* text-yellow">"+++++++++++",</div>

					<div class="col-lg-3 col-md-1 col-sm-2 text-yellow">"Ubuntu"</div>
					<div class="col-lg-1 col-md-1 col-sm-2 text-red">=></div>
					<div class="col-*-* text-yellow">"+++++++++++++++++",</div>

					<div class="col-lg-3 col-md-1 col-sm-2 text-yellow alignment-right">'Bootstrap'</div>
					<div class="col-lg-1 col-md-1 col-sm-2 text-red">=></div>
					<div class="col-*-* text-yellow">"+++++++",</div>

					<div class="col-lg-2 col-md-1 col-sm-2 text-yellow">"Bash"</div>
					<div class="col-lg-2 col-md-1 col-sm-2 text-red">=></div>
					<div class="col-*-* text-yellow">"+++++",</div>

					<div class="col-lg-2 col-md-1 col-sm-2 text-yellow">"HTML"</div>
					<div class="col-lg-2 col-md-1 col-sm-2 text-red">=></div>
					<div class="col-*-* text-yellow">"+++++++++++",</div>

					<div class="col-lg-2 col-md-1 col-sm-2 text-yellow">"CSS3"</div>
					<div class="col-lg-2 col-md-1 col-sm-2 text-red">=></div>
					<div class="col-*-* text-yellow">"++++++++++++++++",</div>

					<div class="col-lg-2 col-md-1 col-sm-2 text-yellow">"Inglês"</div>
					<div class="col-lg-2 col-md-1 col-sm-2 text-red">=></div>
					<div class="col-*-* text-yellow">"+++++++++++++++++++",</div>

					<div class="col-lg-5 col-md-2 col-sm-2 text-yellow">"NoçãoDeDesign"</div>
					<div class="col-lg-2 col-md-1 col-sm-2 text-red">=></div>
					<div class="col-lg-3 col-*-* text-blue">null</div>					


					<div class="col-*-* text-blank">);</div>
				</div>


				<div class="col-lg-12 col-md-12 col-sm-12">
					<div class="col-lg-2 col-md-1 col-sm-2 text-red">return</div>
					<div class="col-lg-10 col-md-10 col-sm-10 text-blank alignment-left">$conhecimentos;</div>
				</div>
			</div>
			<div class="col-lg-12 col-md-12 col-sm-12">
				<div class="col-lg-12 col-md-12 col-sm-12 text-blank">}</div>
			</div>
		</div>



		<div class="col-lg-2 col-md-12 col-sm-12 bg1">
			<img src="assets/img/profile.jpg" class="img-circle img-thumbnail img-responsive"/>
		</div>
		<div class="col-*-* text-green text-center">_--_--_--_--_--_--_ OUTPUT _--_--_--_--_--_--_</div>
  			<div class="col-lg-5 col-md-12 col-sm-12">
				<div class="col-*-* text-blue new-block text-center">
					Nome:
				</div>
				<div class="col-*-* text-yellow text-center">
					Luan Mark da Silva Borela
				</div>

				<div class="col-*-* text-blue new-block text-center">
					Data de Nascimento:
				</div>
				<div class="col-*-* text-yellow text-center">
					14/11/1198
				</div>

				<div class="col-*-* text-blue new-block text-center">
					Idade:
				</div>
				<div class="col-*-* text-yellow text-center">
					18 anos
				</div>

				<div class="col-*-* text-blue new-block text-center">
					Contato:
				</div>
				<div class="col-*-* text-yellow text-center">
					(54) 981092730
				</div>
			</div>
	</div>
</div>