            <?php
            for ($array_size = 0; $array_size < count($v_params["produtosData"]); $array_size++) {
                $id = $v_params["produtosData"][$array_size]["id_produto"];
                $nome = $v_params["produtosData"][$array_size]["nome_produto"];
                $price = $v_params["produtosData"][$array_size]["preco_produto"];
                $url = $v_params["produtosData"][$array_size]["url_produto"];
                $categoria = $v_params["produtosData"][$array_size]["categoria_produto"];
            
            ?>
            
                <div class="produto-container col-lg-4 col-md-4">
                    <div class="produto col-*-*">
                        <a href= <?php echo "'buyPage.php?produto=".$nome."&id=".$id."'";?> class="wrap-link">
                            <div class="wrap">
                                <div class="front">
                                    <img <?php echo 'src= "'.$url.'" />'; ?>
                                    <p class="entypo-mobile"><?php echo $nome?> </p>
                                </div>
                                <div class="back">
                                    <h1 class="entypo-mobile"><?php echo "<br>R$ ".$price?></h1>
                                    <p><?php echo $nome."<br><br>".$categoria?></p>
                                </div>
                            </div>
                        </a>
                    </div>
                </div>
            <?php
            
            }
            
            ?>