            <?php
                $id = $v_params["id_produto"];
                $nome = $v_params["nome_produto"];
                $price = $v_params["preco_produto"];
                $url = $v_params["url_produto"];
                $categoria = $v_params["categoria_produto"];
            ?>
            <div class="produto-container col-lg-4 col-md-4">
                <div class="produto col-*-*">
                    <a href= <?php echo "'buyPage.php?produto=".$nome."&id=".$id."'";?> id="wrap-link">
                        <div class="wrap">
                            <div class="front">
                                <img <?php echo 'src= "'.$url.'" />'; ?>
                                <p class="entypo-mobile"><?php echo $nome?> </p>
                            </div>
                            <div class="back">
                                <h1 class="entypo-mobile"><?php echo "<br>R$ ".$price?></h1>
                                <p><?php echo $nome."<br><br>".$categoria?></p>
                            </div>
                        </div>
                    </a>
                </div>
            </div>
            <div class="produto-container col-lg-4 col-md-4">
                <div class="produto col-*-*">
                    <a href= <?php echo "'buyPage.php?produto=".$nome."&id=".$id."'";?> id="wrap-link">
                        <div class="wrap">
                            <div class="front">
                                <img <?php echo 'src= "'.$url.'" />'; ?>
                                <p class="entypo-mobile"><?php echo $nome?> </p>
                            </div>
                            <div class="back">
                                <h1 class="entypo-mobile"><?php echo "<br>R$ ".$price?></h1>
                                <p><?php echo $nome."<br><br>".$categoria?></p>
                            </div>
                        </div>
                    </a>
                </div>
            </div>
            <div class="produto-container col-lg-4 col-md-4">
                <div class="produto col-*-*">
                    <a href= <?php echo "'buyPage.php?produto=".$nome."&id=".$id."'";?> id="wrap-link">
                        <div class="wrap">
                            <div class="front">
                                <img <?php echo 'src= "'.$url.'" />'; ?>
                                <p class="entypo-mobile"><?php echo $nome?> </p>
                            </div>
                            <div class="back">
                                <h1 class="entypo-mobile"><?php echo "<br>R$ ".$price?></h1>
                                <p><?php echo $nome."<br><br>".$categoria?></p>
                            </div>
                        </div>
                    </a>
                </div>
            </div>