
<div class="sidebar col-lg-2 col-md-2 float-right">
    <a class="sidebar-item" href="#">
        <p>Item sidebar 1</p> 
    </a>
    <a class="sidebar-item" href="#">
        <p>Item sidebar 2</p> 
    </a>
    <a class="sidebar-item" href="#">
        <p>Item sidebar 3</p>
    </a>
    <a class="sidebar-item" href="#">
        <p>Item sidebar 4</p>
    </a>
    <a class="sidebar-item" href="#">
        <p>Item sidebar 5</p>
    </a>
    <a class="sidebar-item" href="#">
        <p>Item sidebar 6</p>
    </a>
    <a class="sidebar-item" href="#">
        <p>Item sidebar 7</p>
    </a>
</div>